CC = gcc
CFLAGS = -Wall -Wextra -g
INCLUDES = -Iinclude
SRC = $(wildcard src/*.c)
OBJDIR = build
OBJ = $(patsubst src/%.c,$(OBJDIR)/%.o,$(SRC))
EXEC = assembler
TEST_EXEC = assembler_test

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^

test: CFLAGS += -DTEST_MODE
test: $(OBJ)
	$(CC) $(CFLAGS) -o $(TEST_EXEC) $^

$(OBJDIR)/%.o: src/%.c
	mkdir -p $(OBJDIR)
	$(CC) $(CFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -rf $(OBJDIR) $(EXEC) $(TEST_EXEC)

.PHONY: all test